org: raravi
app: notes-server-lambda
service: notes-server-lambda
frameworkVersion: ^3.23.0

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    APP_DB: ${self:custom.secrets.APP_DB}
    APP_SECRETORKEY: ${self:custom.secrets.APP_SECRETORKEY}
    APP_EMAIL: ${self:custom.secrets.APP_EMAIL}
    APP_PASSWORD: ${self:custom.secrets.APP_PASSWORD}
    APP_RESETEMAIL: ${self:custom.secrets.APP_RESETEMAIL}
    APP_RESETLINK: ${self:custom.secrets.APP_RESETLINK}
    APP_VALIDATELINK: ${self:custom.secrets.APP_VALIDATELINK}
    APP_CLIENTURL: ${self:custom.secrets.APP_CLIENTURL}

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
